sylius_grid:
  grids:
    hello_jonzz_sylius_job_plugin_admin_job:
      driver:
        name: doctrine/orm
        options:
          class: HelloJonzz\SyliusJobPlugin\Entity\Job
      sorting:
        code: asc
      limits: [10, 25, 50]
      fields:
        code:
          type: string
          label: sylius.ui.code
          sortable: ~
        title:
          type: string
          label: sylius.ui.title
          sortable: ~

      filters:
        search:
          type: string
          label: sylius.ui.search
          options:
            fields: [code]
        title:
          type: string

      actions:
        main:
          create:
            type: create
        item:
          update:
            type: update
          delete:
            type: delete
        bulk:
          delete:
            type: delete
